### ISSUE TITLE
a few issues

### ISSUE THREAD

**Issue by GothkittyGirl** [megoesrawr/Modern-LWC#113]
**LWC Version (/lwc admin version): 2.0.7** 
**Server version (/version): git-spigot-69774b3-671581e (mc: 1.13) (implementing api version 1.13-r0.1-snapshot)** 

**Short five word summary of issue: double doors and chest issue** 

**Detailed description of problem: double doors dont open together. chests gui sometimes wont open. some chests relocking after unlock command ran.**

**If there was an error in console, put it here:**
```
<no errors so far just the issues ingame>
```

**Comment by megoesrawr** [comment]
Try this version: http://jenkins.theemeraldage.com:8080/job/Modern%20LWC/lastSuccessfulBuild/artifact/target/Modern-LWC-2.0.8-snapshot.jar

**Comment by GothkittyGirl** [comment]
running that version atm

**Comment by GothkittyGirl** [comment]
yea ingame version lists 2.0.7 even tho im running 2.0.8 download and still the same thing :/

**Comment by megoesrawr** [comment]
Ah. I dont know why but i cantr seem to fix doors. I think its a spigot issue, but idk. I will try again when spigot 1.13 is out of alpha.

**Comment by Tsuser1** [comment]
Hey, try our latest build on Jenkins, I just merged PR #114 referencing this issue.

**Comment by GothkittyGirl** [comment]
ok fixed now that i seen the new update

**Comment by k0nker** [comment]
Having this issue on the latest version released on spigotmc.org

**Comment by GothkittyGirl** [comment]
doors still a issue but you said your having problem with that but it would seem that the chests are fixed now. locked and unlocked ones

**Comment by k0nker** [comment]
This issue has been happening on and off all morning for us using latest versions of all plugins and spigot.  I would venture to say it's not fixed.

**Comment by k0nker** [comment]
Issue has been happening all day for us with latest versions from Jenkins. Just did another update about 30 minutes ago to be sure, and the issue with chests happened again just now.

**Comment by Tsuser1** [comment]
Fixed by double chest and double door improvement/fix commits.

**Issue closed.**
